[2021-07-19 09:10:42,547] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.insert_data_to_db 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-19 09:10:42,714] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.insert_data_to_db 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-19 09:10:42,715] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 09:10:42,715] {taskinstance.py:1088} INFO - Starting attempt 4 of 4
[2021-07-19 09:10:42,715] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 09:10:43,071] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): insert_data_to_db> on 2021-07-18T07:54:25.449895+00:00
[2021-07-19 09:10:43,076] {standard_task_runner.py:52} INFO - Started process 2822 to run task
[2021-07-19 09:10:43,081] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'autobot', 'insert_data_to_db', '2021-07-18T07:54:25.449895+00:00', '--job-id', '109', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/AutoBot.py', '--cfg-path', '/tmp/tmpponnhe4m', '--error-file', '/tmp/tmpdx7q1sdl']
[2021-07-19 09:10:43,082] {standard_task_runner.py:77} INFO - Job 109: Subtask insert_data_to_db
[2021-07-19 09:10:44,286] {logging_mixin.py:104} INFO - Running <TaskInstance: autobot.insert_data_to_db 2021-07-18T07:54:25.449895+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-19 09:10:45,833] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=autobot
AIRFLOW_CTX_TASK_ID=insert_data_to_db
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T07:54:25.449895+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-18T07:54:25.449895+00:00
[2021-07-19 09:10:47,443] {python.py:151} INFO - Done. Returned value was: None
[2021-07-19 09:10:47,757] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=autobot, task_id=insert_data_to_db, execution_date=20210718T075425, start_date=20210719T091042, end_date=20210719T091047
[2021-07-19 09:10:48,477] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-19 09:10:49,000] {local_task_job.py:151} INFO - Task exited with return code 0
