[2021-07-19 09:14:55,790] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.insert_data_to_db 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-19 09:14:55,950] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.insert_data_to_db 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-19 09:14:55,950] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 09:14:55,950] {taskinstance.py:1088} INFO - Starting attempt 5 of 5
[2021-07-19 09:14:55,950] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 09:14:56,305] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): insert_data_to_db> on 2021-07-18T07:54:25.449895+00:00
[2021-07-19 09:14:56,308] {standard_task_runner.py:52} INFO - Started process 3071 to run task
[2021-07-19 09:14:56,311] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'autobot', 'insert_data_to_db', '2021-07-18T07:54:25.449895+00:00', '--job-id', '112', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/AutoBot.py', '--cfg-path', '/tmp/tmpsgo2dvfl', '--error-file', '/tmp/tmpst9fqjk3']
[2021-07-19 09:14:56,311] {standard_task_runner.py:77} INFO - Job 112: Subtask insert_data_to_db
[2021-07-19 09:14:57,519] {logging_mixin.py:104} INFO - Running <TaskInstance: autobot.insert_data_to_db 2021-07-18T07:54:25.449895+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-19 09:14:59,060] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=autobot
AIRFLOW_CTX_TASK_ID=insert_data_to_db
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T07:54:25.449895+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-18T07:54:25.449895+00:00
[2021-07-19 09:15:00,589] {python.py:151} INFO - Done. Returned value was: None
[2021-07-19 09:15:00,891] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=autobot, task_id=insert_data_to_db, execution_date=20210718T075425, start_date=20210719T091455, end_date=20210719T091500
[2021-07-19 09:15:01,618] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-19 09:15:02,230] {local_task_job.py:151} INFO - Task exited with return code 0
