[2021-07-15 09:19:49,418] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-07-15T09:18:15.649934+00:00 [queued]>
[2021-07-15 09:19:49,632] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-07-15T09:18:15.649934+00:00 [queued]>
[2021-07-15 09:19:49,632] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 09:19:49,632] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-15 09:19:49,632] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 09:19:49,644] {taskinstance.py:1107} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-07-15T09:18:15.649934+00:00
[2021-07-15 09:19:49,647] {standard_task_runner.py:52} INFO - Started process 4313 to run task
[2021-07-15 09:19:49,653] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2021-07-15T09:18:15.649934+00:00', '--job-id', '44', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpd2tdbvgl', '--error-file', '/tmp/tmpgzldzxs_']
[2021-07-15 09:19:49,654] {standard_task_runner.py:77} INFO - Job 44: Subtask is_api_available
[2021-07-15 09:19:49,903] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2021-07-15T09:18:15.649934+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-15 09:19:50,153] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-07-15T09:18:15.649934+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-15T09:18:15.649934+00:00
[2021-07-15 09:19:50,153] {http.py:101} INFO - Poking: api/
[2021-07-15 09:19:50,158] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-07-15 09:19:50,159] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-07-15 09:19:50,478] {base.py:248} INFO - Success criteria met. Exiting.
[2021-07-15 09:19:50,482] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20210715T091815, start_date=20210715T091949, end_date=20210715T091950
[2021-07-15 09:19:50,647] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-15 09:19:50,664] {local_task_job.py:151} INFO - Task exited with return code 0
