[2021-07-19 09:24:07,914] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.save_data 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-19 09:24:08,078] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.save_data 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-19 09:24:08,078] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 09:24:08,078] {taskinstance.py:1088} INFO - Starting attempt 8 of 8
[2021-07-19 09:24:08,078] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 09:24:08,434] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): save_data> on 2021-07-18T07:54:25.449895+00:00
[2021-07-19 09:24:08,437] {standard_task_runner.py:52} INFO - Started process 3643 to run task
[2021-07-19 09:24:08,440] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'autobot', 'save_data', '2021-07-18T07:54:25.449895+00:00', '--job-id', '123', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/AutoBot.py', '--cfg-path', '/tmp/tmpdr4g2g2z', '--error-file', '/tmp/tmp0ln223c8']
[2021-07-19 09:24:08,441] {standard_task_runner.py:77} INFO - Job 123: Subtask save_data
[2021-07-19 09:24:09,651] {logging_mixin.py:104} INFO - Running <TaskInstance: autobot.save_data 2021-07-18T07:54:25.449895+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-19 09:24:11,173] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=autobot
AIRFLOW_CTX_TASK_ID=save_data
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T07:54:25.449895+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-18T07:54:25.449895+00:00
[2021-07-19 09:24:11,727] {python.py:151} INFO - Done. Returned value was: None
[2021-07-19 09:24:12,014] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=autobot, task_id=save_data, execution_date=20210718T075425, start_date=20210719T092407, end_date=20210719T092412
[2021-07-19 09:24:12,748] {taskinstance.py:1265} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2021-07-19 09:24:12,790] {local_task_job.py:151} INFO - Task exited with return code 0
